import type { Metadata } from "next";

// import { ClerkProvider, } from '@clerk/nextjs'

import "./globals.css";
import StoreProvider from "@/components/provider/redux-store-provider";
import { ModalProvider } from "@/components/provider/modal-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <StoreProvider>
      <ModalProvider />
      <html lang="en">
        <body
          className={` antialiased`}
        >
          <section className="container mx-auto max-w-7xl px-4 md:px-6 h-screen">
            {children}
          </section>
        </body>
      </html>

    </StoreProvider>
    // </ClerkProvider>
  );
}
