export const MODAL_TYPE = {
    ALERT_MODAL: "ALERT_MODAL",
    TRANSACTION: "TRANSACTION",
    BANK_ACCOUNT: "BANK_ACCOUNT",
    TRX_NAME: 'TRX_NAME',
    SHOPKEEPER: 'SHOPKEEPER',
    SHOPKEEPER_PAYMENT: 'SHOPKEEPER_PAYMENT',
    LOAN: 'LOAN',
    LOAN_PAYMENT: 'LOAN_PAYMENT',
    FINANCIER: 'FINANCIER',
    LOADING: 'LOADING',
    ASSIGN_TRX_NAME: 'ASSIGN_TRX_NAME',
    ITEM_UNIT: 'ITEM_UNIT',
} as const

export const RESTORE_MODAL_TYPE = {
    RESTORE_TRX_NAME: "RESTORE_TRX_NAME",
    RESTORE_BANK: "RESTORE_BANK",
    RESTORE_SHOPKEEPER: "RESTORE_SHOPKEEPER",
    RESTORE_LOAN_FINANCIER: 'RESTORE_LOAN_FINANCIER',
    RESTORE_ITEM_UNIT: 'RESTORE_ITEM_UNIT',
    RESTORE_BUDGET: 'RESTORE_BUDGET',
} as const