export const MODAL_TYPE = {
    ALERT_MODAL: "ALERT_MODAL",
    TRANSACTION: "TRANSACTION",
    BANK_ACCOUNT: "BANK_ACCOUNT",
    TRX_NAME: 'TRX_NAME',
    SHOPKEEPER: 'SHOPKEEPER',
    SHOPKEEPER_PAYMENT: 'SHOPKEEPER_PAYMENT',
    LOAN: 'LOAN',
    LOAN_PAYMENT: 'LOAN_PAYMENT',
    FINANCIER: 'FINANCIER',
    LOADING: 'LOADING',
    ASSIGN_TRX_NAME: 'ASSIGN_TRX_NAME',
} as const